### ISSUE TITLE
Collapse texts in "..." with css

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [Crazy-Unicooorn/crazy-guessr#10]

**Comment by Crazy-Unicooorn** [comment]
```CSS
.singleline-text {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
